server:
  port: 8086

spring:

  profiles:
    active: local

  application:
    name: vnatives-commerce-pricing-discount-service

  data:
    redis:
      host: vnatives-redis
      port: 6379
      timeout: 2000ms

  cache:
    type: redis

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    health:
      probes:
        enabled: true
      show-details: when_authorized
    web:
      exposure:
        include: health,info,metrics,prometheus


logging:
  file:
    name: /logs/${spring.application.name}.json
  pattern:
    console: "%msg%n"

springdoc:
  swagger-ui:
    enabled: true
